---
- name: Create a VMware virtual machine
  hosts: 10.4.11.10
  connection: local
  gather_facts: no
  tasks:
    - name: Gather all registered virtual machines
      community.vmware.vmware_vm_info:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
      register: vm_info
    - name: Display name of all VMs
      debug:
        #var: vm_info.virtual_machines
        msg: "{{ item.guest_name }}"
      loop: "{{ vm_info.virtual_machines }}"
      when: item.guest_name is defined
    - name: Send VM names to webhook
      uri:
        url: "http://10.4.14.120:5000/webhook"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "vm_names": [
              {% for vm in vm_info.virtual_machines %}
                "{{ vm.name }}"{% if not loop.last %},{% endif %}
              {% endfor %}
            ]
          }
        body_format: json
